use serde::{Deserialize, Serialize};

/// Stable id generated by the app for one local installation.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub struct DeviceInstallationId(pub String);
