[package]
name = "fman-nostr"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
async-trait.workspace = true
base64.workspace = true
chacha20poly1305 = "0.10"
ciborium = { workspace = true }
fedi-decentralized-domain = { path = "../../domain" }
fedi-decentralized-manifold-environment = { path = "../../manifold-environment" }
fedi-decentralized-nostr = { path = "../../nostr" }
fedi-decentralized-nostr-clients = { path = "../../nostr-clients" }
fedi-decentralized-service-fleet-manager = { path = "../../service-fleet-manager" }
fman-core = { path = "../core" }
hex = "0.4"
hmac = "0.12"
nostr-sdk = "0.44"
secp256k1 = "0.30"
serde = { workspace = true }
serde_json = "1"
sha2.workspace = true
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tracing = "0.1"

[dev-dependencies]
blind-rsa-signatures = "0.17"
fedi-credential-sdk-protocol.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
